### ISSUE TITLE
crash inside packet_handler

### ISSUE THREAD

**Issue by alext234** [alext234/LibPcap#19]
when processing a pcap file the following crash occurs
```
==5330==ERROR: AddressSanitizer: unknown-crash on address 0x629000005200 at pc 0x56ad69 bp 0x7fffffffce90 sp 0x7fffffffce80
READ of size 26334 at 0x629000005200 thread T0
    #0 0x56ad68 in unsigned char* std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<unsigned char>(unsigned char const*, unsigned char const*, unsigned char*) /usr/include/c++/4.9/bits/stl_algobase.h:378
    #1 0x56ac6f in unsigned char* std::__copy_move_a<false, unsigned char const*, unsigned char*>(unsigned char const*, unsigned char const*, unsigned char*) /usr/include/c++/4.9/bits/stl_algobase.h:396
    #2 0x573f37 in unsigned char* std::__copy_move_a2<false, unsigned char const*, unsigned char*>(unsigned char const*, unsigned char const*, unsigned char*) /usr/include/c++/4.9/bits/stl_algobase.h:434
    #3 0x5734d5 in unsigned char* std::copy<unsigned char const*, unsigned char*>(unsigned char const*, unsigned char const*, unsigned char*) /usr/include/c++/4.9/bits/stl_algobase.h:466
    #4 0x57489f in unsigned char* std::__uninitialized_copy<true>::__uninit_copy<unsigned char const*, unsigned char*>(unsigned char const*, unsigned char const*, unsigned char*) /usr/include/c++/4.9/bits/stl_uninitialized.h:93
    #5 0x573fb7 in unsigned char* std::uninitialized_copy<unsigned char const*, unsigned char*>(unsigned char const*, unsigned char const*, unsigned char*) /usr/include/c++/4.9/bits/stl_uninitialized.h:126
    #6 0x573575 in unsigned char* std::__uninitialized_copy_a<unsigned char const*, unsigned char*, unsigned char>(unsigned char const*, unsigned char const*, unsigned char*, std::allocator<unsigned char>&) /usr/include/c++/4.9/bits/stl_uninitialized.h:279
    #7 0x57258e in void std::vector<unsigned char, std::allocator<unsigned char> >::_M_assign_aux<unsigned char const*>(unsigned char const*, unsigned char const*, std::forward_iterator_tag) /usr/include/c++/4.9/bits/vector.tcc:293
    #8 0x570ab9 in void std::vector<unsigned char, std::allocator<unsigned char> >::_M_assign_dispatch<unsigned char const*>(unsigned char const*, unsigned char const*, std::__false_type) /usr/include/c++/4.9/bits/stl_vector.h:1336
    #9 0x56f2f1 in void std::vector<unsigned char, std::allocator<unsigned char> >::assign<unsigned char const*, void>(unsigned char const*, unsigned char const*) /usr/include/c++/4.9/bits/stl_vector.h:508
    #10 0x56e382 in Pcap::Dev::CPcapWrapper::packet_handler(unsigned char*, pcap_pkthdr const*, unsigned char const*) /home/u/NetCapStatistics/LibPcap/cpppcap.cpp:124
    #11 0x587113 in pcap_offline_read savefile.c:527
    #12 0x576e8e in pcap_loop pcap.c:890
    #13 0x56c396 in Pcap::Dev::loop() /home/u/NetCapStatistics/LibPcap/cpppcap.cpp:147
    #14 0x4d5391 in processPcapList(std::shared_ptr<PacketStat>&, std::vector<std::string, std::allocator<std::string> > const&) /home/u/NetCapStatistics/ncstat.cpp:23
    #15 0x4d62a5 in main /home/u/NetCapStatistics/ncstat.cpp:91
    #16 0x7ffff65ba82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #17 0x4d4288 in _start (/home/u/NetCapStatistics/build/ncstat+0x4d4288)

0x629000009200 is located 0 bytes to the right of 16384-byte region [0x629000005200,0x629000009200)
allocated by thread T0 here:
    #0 0x7ffff6f52527 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x57527)
    #1 0x587c2a in pcap_check_header sf-pcap.c:401

SUMMARY: AddressSanitizer: unknown-crash /usr/include/c++/4.9/bits/stl_algobase.h:378 unsigned char* std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<unsigned char>(unsigned char const*, unsigned char const*, unsigned char*)
Shadow bytes around the buggy address:
  0x0c527fff89f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fff8a00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fff8a10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fff8a20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fff8a30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c527fff8a40:[00]00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c527fff8a50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c527fff8a60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c527fff8a70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c527fff8a80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c527fff8a90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==5330==ABORTING
```

**Comment by alext234** [comment]
fixed at https://github.com/alext234/LibPcap/commit/8639a2f30eec7dd30fdead2a5f60a0ba74b3259e 
use caplen instead of len. based on libpcap man page, caplen is the amount of data available to user.
